# ===================================
# FILE: .env.example
# Upload this to GitHub as ".env.example"
# ===================================

# Divine Acquisition - Environment Variables Template
# This shows what environment variables are needed

# Facebook Ads API Configuration
FACEBOOK_ACCESS_TOKEN=your_facebook_access_token_here
FACEBOOK_AD_ACCOUNT_ID=your_ad_account_id_here

# GoHighLevel API Configuration  
GHL_API_KEY=your_ghl_api_key_here
GHL_LOCATION_ID=your_ghl_location_id_here

# Database Configuration (Optional - uses in-memory if not provided)
DATABASE_URL=postgresql://username:password@host:port/database

# Server Configuration
NODE_ENV=production
PORT=3000

# Security (Optional - generate random strings)
JWT_SECRET=your-super-secret-jwt-key-here
WEBHOOK_SECRET=your-webhook-verification-secret

# Logging (Optional)
LOG_LEVEL=info

# ===================================
# FILE: .env (FOR VERCEL ENVIRONMENT VARIABLES)
# DO NOT upload this to GitHub - only use in Vercel dashboard
# ===================================

# Your actual credentials for Vercel environment variables:
FACEBOOK_ACCESS_TOKEN=EAALAROJZAgz8BPHTfzQtnpTMUJc8FjkbZCZCfTxfJ6eJ1RSNd6xUiu3Q13iFatWecVq8THsTMrorvN95iCc6G0ZBcFZAEapPVwqFx7MXczSfsOPQF25PAGo8HLCqlcPp5LGrnlyXYsXcq356YhXOvddtYYcJv1pDGzhBBHuupg2WWzrv8tPak7ZCkz9kupEZClCZAwZDZD
FACEBOOK_AD_ACCOUNT_ID=994917815468301
GHL_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2NhdGlvbl9pZCI6ImpXaDFUdGxDalVEZVpaMjdSa2tJIiwidmVyc2lvbiI6MSwiaWF0IjoxNzEzNDgxMDU3NTg3LCJzdWIiOiJiVkZKT1hwNWJvd1U0NjRjdlhuQyJ9.MimUheKBgkSBqgh5d73CfrpXfTkKInSjjxbC-LPbAaU
GHL_LOCATION_ID=jWh1TtlCjUDeZZ27RkkI
NODE_ENV=production
PORT=3000

# ===================================
# FILE: .gitignore
# Upload this to GitHub as ".gitignore"
# ===================================

# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Environment variables (keep secrets safe)
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Logs
logs
*.log

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# Operating System Files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# IDE Files
.vscode/
.idea/
*.swp
*.swo
*~

# Build outputs
dist/
build/
out/

# Vercel
.vercel

# Database
*.sqlite
*.db

# Cache
.cache/
.parcel-cache/